// @generated by scripts/sync-worker-shared.js — DO NOT EDIT.
// Edit src/shared/<name>.js instead, then run `npm run sync:worker`.

'use strict';

// Canonical limit-provider ids, aliases, hub collapse policy, and capability
// declarations. Identity is always a stable id (case-insensitive) or an alias
// of one — never a display label such as "GitHub Copilot" or "Z.ai".

const DEFAULT_CAPABILITIES = Object.freeze({
  supportsPartialRefresh: false,
  supportsAccountScope: false,
  supportsQuotaPools: false
});

// Multi-account providers keep distinct rows in hub aggregateLimits() when they
// carry a configured accountKey. Everyone else still collapses by canonical id.
const COLLAPSE_BY_ACCOUNT = new Set([
  'claude',
  'codex',
  'opencode',
  'openrouter',
  'thirdparty',
  'mimo'
]);

// Providers the Monitor collector actually probes. Ingest still accepts the
// extra canonical ids below (Potluck / third-party rows) without implying we
// can refresh them.
const COLLECTED_PROVIDER_IDS = new Set([
  'claude',
  'codex',
  'opencode',
  'cursor',
  'antigravity',
  'kimi',
  'grok',
  'copilot',
  'mimo',
  'zai',
  'zaiteam',
  'kiro',
  'deepseek',
  'openrouter',
  'minimax',
  'volcengine',
  'qoder',
  'ollama',
  'thirdparty'
]);

const LOCAL_QUOTA_PROVIDER_IDS = new Set(['ollama']);

// Allowlist order is part of the ingest contract: unknown ids are dropped.
const CANONICAL_PROVIDER_IDS = Object.freeze([
  'claude',
  'codex',
  'cursor',
  'antigravity',
  'opencode',
  'openrouter',
  'deepseek',
  'minimax',
  'mimo',
  'grok',
  'copilot',
  'kiro',
  'zai',
  'volcengine',
  'qoder',
  'zaiteam',
  'kimi',
  'ollama',
  'thirdparty',
  'brave-search',
  'gemini-cli',
  'kimchi',
  'nvidia',
  'opencode-go',
  'qoder-cn',
  'tavily'
]);

const PROVIDERS = Object.create(null);
for (const id of CANONICAL_PROVIDER_IDS) {
  const multiAccount = COLLAPSE_BY_ACCOUNT.has(id);
  PROVIDERS[id] = Object.freeze({
    id,
    collapse: multiAccount ? 'account' : 'provider',
    local: LOCAL_QUOTA_PROVIDER_IDS.has(id),
    capabilities: Object.freeze({
      supportsPartialRefresh: COLLECTED_PROVIDER_IDS.has(id),
      supportsAccountScope: multiAccount,
      supportsQuotaPools: false
    })
  });
}

// Old / regional ids rewrite to a canonical id. Optional region fills in only
// when the payload omitted one. Aliases must not collide with canonical ids.
const PROVIDER_ALIASES = Object.freeze({
  glm: Object.freeze({ id: 'zai', region: 'global' }),
  'glm-cn': Object.freeze({ id: 'zai', region: 'cn' }),
  'zai-team': Object.freeze({ id: 'zaiteam' }),
  'minimax-cn': Object.freeze({ id: 'minimax', region: 'cn' }),
  // Local Ollama usage — must not be rewritten onto a cloud quota vendor.
  'ollama-local': Object.freeze({ id: 'ollama' })
});

for (const [alias, target] of Object.entries(PROVIDER_ALIASES)) {
  if (PROVIDERS[alias]) {
    throw new Error(`limit provider alias "${alias}" collides with a canonical id`);
  }
  if (!target || !PROVIDERS[target.id]) {
    throw new Error(`limit provider alias "${alias}" points at unknown id "${target && target.id}"`);
  }
}

function resolveProviderIdentity(value) {
  const raw = String(value || '').trim().toLowerCase();
  if (!raw) return null;
  if (PROVIDERS[raw]) return { id: raw, region: '' };
  const alias = PROVIDER_ALIASES[raw];
  if (!alias) return null;
  return { id: alias.id, region: alias.region || '' };
}

function canonicalProviderId(value) {
  const identity = resolveProviderIdentity(value);
  return identity ? identity.id : null;
}

function collapsesByAccount(providerId) {
  return PROVIDERS[providerId]?.collapse === 'account';
}

function providerCapabilities(providerId) {
  const capabilities = PROVIDERS[providerId]?.capabilities;
  return capabilities ? { ...capabilities } : { ...DEFAULT_CAPABILITIES };
}

function isLocalQuotaProvider(providerId) {
  return Boolean(PROVIDERS[providerId]?.local);
}

module.exports = {
  CANONICAL_PROVIDER_IDS,
  canonicalProviderId,
  collapsesByAccount,
  isLocalQuotaProvider,
  providerCapabilities,
  resolveProviderIdentity
};
